# Generated by Django 2.1 on 2018-10-12 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeView', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='dateVal',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
