# Generated by Django 2.1 on 2018-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeView', '0002_auto_20181012_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='relevantFactors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='symptoms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
