# Generated by Django 2.1 on 2018-10-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeView', '0003_auto_20181013_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='score',
            field=models.IntegerField(blank=True),
        ),
    ]
