# Generated by Django 2.1 on 2018-10-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeView', '0004_auto_20181016_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='score',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
